### ISSUE TITLE
Sandbox.h?

### ISSUE THREAD

**Issue by ghost** [DeadlyFugu/wav2png#1]
Hi there, I'm trying to build your code here....but running into the error:
 fatal error: sandbox.h: No such file or directory  
   39 | #include <sandbox.h>  
What does this mean?  I haven't been able to figure it out yet.
Cheers!

**Comment by DeadlyFugu** [comment]
I'm not sure how you found this old project or how it would be useful to anybody haha. Steganography maybe?

It appears there were some issues I never noticed due to not testing it on other systems. I pushed some changes so it should compile and run now. If you still have any issues let me know, preferably including more details (full console output and your operating system).
